version: "2"

services:
  client:
    image: node:latest              
    command: sh -c 'echo "fooo" && yarn install && yarn run serve'
    working_dir: /opt/client
    volumes:
      - ./client:/opt/client
    ports:
      - "8080:8080"
      - "8000:8000" 
  go-server:    
    build:    
      context: ./go-server   
      dockerfile: ./src/go-server/Dockerfile
    volumes:
        - ./go-server/:/go/src/github.com/wyrdnixx/go-server
    ports:
      - "5000:5000"
    environment:
       API_PORT: 5000
    depends_on:
      - server-database                
#  server-node:
#    build: ./server
#    ports:
#      - 8081:8081
#    volumes:
#      - ./server:/data
#    depends_on: 
#      - server-database
#    environment:
#       DATABASE_URL: server-database      
#       MYSQL_ROOT_PASSWORD: mysqlroot
#       MYSQL_USER: user
#       MYSQL_PASSWORD: pass
#       MARIADB_DATABASE: appdb  
#    depends_on:
#      - server-database
  server-database:
    image: mariadb:latest
    volumes:
      - ./database:/var/lib/mysql 
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=mysqlroot
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MARIADB_DATABASE=appdb
      - MYSQL_MAX_ALLOWED_PACKET=1024M
      - MYSQL_INNODB_BUFFER_POOL_SIZE=1G
      - MYSQL_INNODB_LOG_FILE_SIZE=256M
      - MYSQL_INNODB_LOG_BUFFER_SIZE=256M

    
